name: river
channels:
  - intel
dependencies:
  - python=3.6.6
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - numpy
  - bottleneck
  - dask
  - hdf5
  - pip
  - tensorflow

